{ pkgs
, lib
, config
, ...
} @ inputs:
let
  listNixModulesRecusive = import ../../lib/listNixModulesRecusive.nix inputs;
  system = "x86_64-linux";
  # Headless KMSwitch client config, generated by Nix. Connects to the desktop
  # server (192.168.1.42) to receive keyboard+mouse.
  kmswitchClientConf = pkgs.writeText "kmswitch-client.conf" ''
    role = client
    name = hi10max
    pairing_key = a333c71f4bc3a81a0a80d7da7d82912eb14da0f8ed324f56f8b1fa6c3cac4772
    peer = 192.168.1.42
    port = 47801
    hotkey = Win+Esc
    clipboard_sync = true
    mouse_sensitivity = 1.0
    link_timeout_ms = 1500
    ui_port = 0
    open_browser = false
    log_level = info
  '';
in
{
  imports =
    [
      ./boot.nix
      ./hardware.nix
      ./services.nix
    ]
    ++ (listNixModulesRecusive ../../modules/nixos);

  # Use knoopx/niri (configurable touch gestures) for configurable
  # touchscreen and touchpad gesture support.
  nixpkgs.overlays = [
    (final: prev: {
      niri = inputs.niri-touch.packages.${system}.niri.overrideAttrs {
        doCheck = false;
      };
    })
  ];

  programs.feedbackd.enable = true;

  # No lockscreen on the tablet.
  programs.hyprlock.enable = false;

  services.iio-niri = {
    enable = true;
    extraArgs = [ "--monitor" "eDP-1" ];
  };

  hardware.sensor.iio.enable = true;

  system.stateVersion = "25.11";

  networking.hostName = "hi10max";

  # KMSwitch client (headless): receives keyboard+mouse from the desktop server.
  systemd.user.services.kmswitch = {
    description = "KMSwitch client (receives keyboard/mouse from desktop)";
    wantedBy = [ "graphical-session.target" ];
    serviceConfig = {
      ExecStart = "${pkgs.kmswitch}/bin/kmswitch --client --no-ui --config ${kmswitchClientConf}";
      Restart = "on-failure";
      RestartSec = 3;
    };
  };

  nixpkgs = {
    hostPlatform = {
      inherit system;
    };
  };

  # Mobian-equivalent base, tablet/mobile packages and services for hi10max.
  environment.systemPackages = with pkgs; [
    # qt5.qtwayland
    # qt6.qtwayland
    # rygel
    feedbackd
    iio-sensor-proxy
    gnome-settings-daemon
    xdg-desktop-portal-gtk
    gst123
    libcamera
    dconf
    alsa-utils
    busybox
    dosfstools
    e2fsprogs
    hwdata
    kbd
    rtkit
    usbutils
    iputils
    iptables
    iw
    nettools
    wirelesstools
    zstd
    bzip2
    dialog
    gawk
    less
    sudo
    bash-completion
    vim
    usb-modeswitch
    wtype
  ];

  # Route IME activation to the compositor so wvkbd (--auto mode) can
  # auto-appear when an app's text field gains focus.
  environment.variables = {
    GTK_IM_MODULE = lib.mkForce "wayland";
    QT_IM_MODULE = lib.mkForce "wayland";
  };

  programs.dconf.profiles.user.databases = [
    {
      settings = {
        "org/gnome/desktop/a11y/applications" = { screen-keyboard-enabled = true; };
        "org/gnome/desktop/a11y/magnifier" = { cross-hairs-length = lib.gvariant.mkUint32 58; };
        "org/gnome/settings-daemon/plugins/media-keys" = { active = false; };
        "org/gnome/settings-daemon/plugins/power" = { active = false; };
        "org/gnome/settings-daemon/plugins/housekeeping" = { donation-reminder-enabled = false; };
        "org/gnome/settings-daemon/peripherals/touchscreen" = { orientation-lock = true; };
        "org/gnome/desktop/wm/preferences" = { button-layout = "appmenu:"; };
        "org/gnome/desktop/interface" = {
          cursor-blink = true;
          toolkit-accessibility = false;
          clock-show-seconds = false;
          clock-show-unicode = false;
          menu-animation = false;
          toolbar-style = "icons";
          icon-theme = "Adwaita-dark";
        };
        "org/gnome/desktop/input-sources" = { sources = lib.gvariant.mkArray [ "'xkb','us'" ]; };
        "org/sigxcpu/feedbackd" = { profile = "full"; };
        "org/gnome/control-center" = { last-panel = "universal-access"; };
        "org/gnome/settings-daemon/plugins/color" = { night-light-schedule-automatic = false; };
        "org/gnome/desktop/screensaver" = {
          lock-enabled = false;
          lock-delay = lib.gvariant.mkUint32 0;
        };
        "org/gnome/system/location" = { enabled = false; };
      };
    }
  ];

  defaults.wifi = lib.mkForce true;
  defaults.bluetooth = lib.mkForce true;
  defaults.display.width = lib.mkForce 1920;
  defaults.display.height = lib.mkForce 1200;
  defaults.display.idleTimeout = lib.mkForce (15 * 60);
  defaults.display.idleTimeoutAC = lib.mkForce (15 * 60);
  defaults.display.defaultColumnWidthPercent = lib.mkForce 0.5;
  defaults.display.columnWidthPercentPresets = lib.mkForce [ 0.5 0.75 ];
  defaults.display.lockEnabled = lib.mkForce false;

  home-manager.users.${config.defaults.username} = {
    imports = [
      ../../home/${config.defaults.username}.nix
    ];

    programs.vicinae.settings.launcher_window.layer_shell = lib.mkForce {
      enabled = true;
      layer = "overlay";
      keyboard_interactivity = "exclusive";
    };

    # Tablet quick settings for the astal-shell top bar (written to
    # astal-shell/quickSettings.json by the shared astal-shell module).
    services.astal-shell.quickSettings = [
      {
        id = "poweroff";
        icon = "system-shutdown-symbolic";
        label = "Power off";
        command = [ "session-control" "poweroff" ];
        confirm = true;
      }
      {
        id = "virtual-keyboard";
        icon = "input-keyboard-symbolic";
        label = "Toggle virtual keyboard";
        # Absolute path: astal-shell's service env has no PATH to the home
        # packages, so a bare "virtual-keyboard-control" is not found.
        command = [ "${pkgs.virtual-keyboard-control}/bin/virtual-keyboard-control" "toggle" ];
      }
    ];

    programs.niri.config =
      let
        bgColor = config.defaults.colorScheme.palette.base02;
        activeColor = config.defaults.colorScheme.palette.base0D;
        borderColor = config.defaults.colorScheme.palette.base03;
        insertHintRGB = inputs.nix-colors.lib-core.conversions.hexToRGBString " " activeColor;
        xwaylandPath = lib.getExe pkgs.xwayland-satellite;
        gvfsPath = "${config.services.gvfs.package}/lib/gio/modules";
        keyMap = config.defaults.keyMap;
      in
      ''
        input {
            keyboard {
                xkb { layout "${keyMap}"; }
                repeat-delay 600
                repeat-rate 25
                track-layout "global"
            }
            touchpad {
                tap
                dwt
                natural-scroll
                accel-speed 0.2
                accel-profile "adaptive"
                scroll-factor 0.3
            }
            mouse { accel-speed 0.0; }
            trackpoint { accel-speed 0.0; }
            trackball { accel-speed 0.0; }
            tablet { map-to-output "eDP-1"; }
            touchscreen { map-to-output "eDP-1"; }
            warp-mouse-to-focus
            workspace-auto-back-and-forth
        }
        output "eDP-1" {
            background-color "#${bgColor}"
            scale 2
            transform "270"
        }
        screenshot-path "~/Pictures/Screenshots/%Y-%m-%d %H-%M-%S.png"
        prefer-no-csd
        overview {
            zoom 0.7
            backdrop-color "#${bgColor}"
            workspace-shadow { off; }
        }
        layout {
            gaps 12
            background-color "transparent"
            struts { left 0; right 0; top 0; bottom 0; }
            focus-ring {
                width 3
                active-color "#${activeColor}"
            }
            border {
                width 3
                active-color "#${borderColor}"
                inactive-color "#${borderColor}"
            }
            insert-hint { color "rgb(${insertHintRGB} / 50%)"; }
            default-column-width { proportion 0.5; }
            preset-column-widths {
                proportion 0.5
                proportion 0.75
            }
            center-focused-column "never"
        }
        cursor {
            xcursor-theme "default"
            xcursor-size 24
            hide-when-typing
        }
        hotkey-overlay { skip-at-startup; }
        environment { "GIO_EXTRA_MODULES" "${gvfsPath}"; }
        binds {
            "Mod+Period" { toggle-overview; }
            "MouseForward" { toggle-overview; }
            "Mod+J" { spawn "browser"; }
            "Mod+Shift+J" { spawn "file-manager"; }
            "Mod+K" { spawn "pick-project" "editor"; }
            "Mod+Shift+K" { spawn "pi-project"; }
            "Mod+O" { spawn "pick-document" "editor"; }
            "Mod+L" { spawn "terminal"; }
            "Mod+Shift+L" { spawn "pick-project" "terminal"; }
            "Mod+Left" { focus-column-left; }
            "Mod+Right" { focus-column-right; }
            "Mod+Down" { focus-workspace-down; }
            "Mod+Up" { focus-workspace-up; }
            "Mod+D" { focus-window-down-or-top; }
            "Mod+H" { spawn "voice-input-control" "toggle"; }
            "Mod+V" { center-window; }
            "Mod+F" { spawn "sh" "-c" "niri msg action maximize-column; niri msg action center-window"; }
            "Mod+Shift+F" { spawn "window-control" "fullscreen"; }
            "Mod+U" { consume-or-expel-window-left; }
            "Mod+I" { consume-or-expel-window-right; }
            "Mod+Q" { close-window; }
            "Mod+R" { spawn "sh" "-c" "niri msg action switch-preset-column-width; niri msg action center-window"; }
            "Mod+Return" { spawn "window-control" "float-to-corner"; }
            "Mod+Tab" { focus-monitor-next; }
            "Mod+Shift+Tab" { switch-focus-between-floating-and-tiling; }
            "Mod+Shift+Ctrl+L" { quit skip-confirmation=true; }
            "Mod+Shift+Down" { move-column-to-workspace-down; }
            "Mod+Shift+End" { move-workspace-down; }
            "Mod+Shift+Home" { move-workspace-up; }
            "Mod+Shift+Left" { move-column-left; }
            "Mod+Shift+Right" { move-column-right; }
            "Mod+Shift+Up" { move-column-to-workspace-up; }
            "Ctrl+Mod+Shift+Left" { move-window-to-monitor-left; }
            "Ctrl+Mod+Shift+Right" { move-window-to-monitor-right; }
            "Mod+Space" { spawn "vicinae" "toggle"; }
            "Mod+B" { spawn "xdg-open" "vicinae://extensions/vicinae/manage-shortcuts/manage"; }
            "Mod+W" { close-window; }
            "Print" { spawn "niri" "msg" "action" "screenshot" "--show-pointer" "false"; }
            "Shift+Print" { screenshot-window; }
            "Mod+Shift+P" { spawn "pick-agent"; }
            "Mod+P" { spawn "kitty" "sh" "-c" "cd ~/.pi && pi"; }
            "Mod+Shift+Print" { spawn "screen-recording"; }
            "Ctrl+Mod+Shift+Print" { spawn "screen-recording" "--mode" "portal"; }
            "Mod+G" { spawn "wl-kbptr" "-o" "modes=floating,click" "-o" "mode_floating.source=detect"; }
            "XF86AudioLowerVolume" { spawn "volume-control" "down"; }
            "XF86AudioMute" { spawn "volume-control" "mute"; }
            "XF86AudioNext" { spawn "media-control" "next"; }
            "XF86AudioPlay" { spawn "media-control" "play-pause"; }
            "XF86AudioPrev" { spawn "media-control" "previous"; }
            "XF86AudioRaiseVolume" { spawn "volume-control" "up"; }
            "XF86AudioStop" { spawn "media-control" "stop"; }
            "XF86MonBrightnessDown" { spawn "brightness-control" "down"; }
            "XF86MonBrightnessUp" { spawn "brightness-control" "up"; }
        }
        switch-events {
            lid-close { spawn "display-control" "power-off-monitors"; }
            tablet-mode-off { spawn "tablet-mode-control" "off"; }
            tablet-mode-on { spawn "tablet-mode-control" "on"; }
        }
        window-rule {
            draw-border-with-background false
            geometry-corner-radius 8 8 8 8
            clip-to-geometry true
        }
        window-rule {
            match is-floating=true
            geometry-corner-radius 16 16 16 16
        }
        window-rule {
            match app-id="scrcpy"
            default-column-width { fixed 472; }
            open-floating false
            geometry-corner-radius 18 18 18 18
        }
        window-rule {
            match app-id="org.gnome.NautilusPreviewer"
            default-window-height { proportion 0.75; }
            open-floating true
        }
        window-rule {
            match app-id="io.bassi.Amberol"
            match app-id="plexamp"
            default-column-width { proportion 0.25; }
        }
        window-rule {
            match title="/dev/video0"
            default-column-width { fixed 400; }
            default-window-height { fixed 300; }
            open-floating true
            open-focused false
            default-floating-position relative-to="bottom-right" x=12 y=12
        }
        window-rule {
            match app-id="scrcpy"
            match title="[Ll]ogin"
            match title="Photos"
            match title="[Ss]ign-?in"
            match title="[Pp]assword"
            match title="Calendar"
            match title="Meet"
            match title="Notion"
            match title="Slack"
            match title="Reddit"
            match title="Telegram"
            match title="Discord"
            match title="WhatsApp"
            match title="Vicinae Launcher"
            match title="Gmail"
            match app-id="org.gnome.Nautilus"
            block-out-from "screen-capture"
        }
        window-rule {
            match is-active=false
            opacity 0.9
        }
        window-rule {
            match is-floating=true
            opacity 1.0
        }
        layer-rule {
            match namespace="notifications"
            block-out-from "screen-capture"
        }
        layer-rule {
            match namespace="^wallpaper$"
            place-within-backdrop true
        }
        gestures { hot-corners { off; }; }
        animations {
            slowdown 0.6
            window-open {
                duration-ms 750
                curve "ease-out-cubic"
            }
            window-close {
                duration-ms 750
                curve "ease-out-cubic"
            }
        }
        xwayland-satellite { path "${xwaylandPath}"; }

        // niri-touch-config gesture includes (knoopx/niri)
        include "touchscreen-gestures.kdl" optional=true
        include "touchpad-gestures.kdl"    optional=true
      '';

    # Gesture KDL files for knoopx/niri (configurable touch gestures).
    # Included via `include` directives in config.kdl above.
    xdg.configFile = {
      "niri/touchscreen-gestures.kdl".text = builtins.readFile ./touchscreen-gestures.kdl;
      "niri/touchpad-gestures.kdl".text = builtins.readFile ./touchpad-gestures.kdl;
    };
  };
}
