{ config, lib, pkgs, ... }:
let
  pairingKey = "a333c71f4bc3a81a0a80d7da7d82912eb14da0f8ed324f56f8b1fa6c3cac4772";
  # Headless KMSwitch server config, generated by Nix.
  serverConf = pkgs.writeText "kmswitch-server.conf" ''
    role = server
    name = desktop
    pairing_key = ${pairingKey}
    port = 47801
    discovery_port = 47802
    # mod+esc toggle between local and remote
    hotkey = Win+Esc
    clipboard_sync = true
    mouse_sensitivity = 1.0
    link_timeout_ms = 1500
    ui_port = 0
    open_browser = false
    log_level = info
  '';
in
{
  systemd.user.services.kmswitch = {
    Unit = {
      Description = "KMSwitch server (shares keyboard/mouse to hi10max)";
      After     = [ "network.target" ];
    };
    Service = {
      ExecStart   = "${pkgs.kmswitch}/bin/kmswitch --server --no-ui --config ${serverConf}";
      Restart     = "on-failure";
      RestartSec  = 3;
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };
}
